packaging_format = 2

id = "paperless-ngx"
name = "Paperless-ngx"
description.en = "Scan, index and archive all your physical documents"
description.fr = "Scannez, triez et archivez tous vos documents papiers"

version = "1.14.5~ynh2"

maintainers = ["Tagada"]

[upstream]
license = "GPL-3.0-or-later"
website = "https://paperless-ngx.com"
demo = "https://demo.paperless-ngx.com/"
admindoc = "https://paperless-ngx.readthedocs.io/en/latest/index.html"
userdoc = "https://paperless-ngx.readthedocs.io/en/latest/usage_overview.html"
code = "https://github.com/paperless-ngx/paperless-ngx"
cpe = "???" # XXX: No CPE yet... check https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=paperless

[integration]
yunohost = ">= 11.0.0"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"
    full_domain = true

    [install.admin]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "user"

    [install.admin_pw]
    ask.en = "Please chose a password for admin user."
    type = "password"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

    [install.is_public_api]
    ask.en = "Should Paperless-ngx API be accessible for apps."
    type = "boolean"
    default = false

[resources]
    [resources.sources]

        [resources.sources.main]
        # This will pre-fetch the asset which can then be deployed during the install/upgrade scripts with :
        #    ynh_setup_source --dest_dir="$install_dir"
        # You can also define other assets than "main" and add --source_id="foobar" in the previous command
        url = "https://github.com/paperless-ngx/paperless-ngx/releases/download/v1.14.5/paperless-ngx-v1.14.5.tar.xz"
        sha256 = "355a5760cbc967c2bd6dcaf89f577aefd5acedd908361377976e04e17c95a8f9"

        # These infos are used by https://github.com/YunoHost/apps/blob/master/tools/autoupdate_app_sources/autoupdate_app_sources.py
        # to auto-update the previous asset urls and sha256sum + manifest version
        # assuming the upstream's code repo is on github and relies on tags or releases
        # See the 'sources' resource documentation for more details

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = "paperless-ngx-*.tar.xz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["consume", "data", "media"]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8095

    [resources.apt]
    packages = "python3, python3-pip, python3-dev, python3-venv, default-libmysqlclient-dev, fonts-liberation, imagemagick, gnupg, libpq-dev, libmagic-dev, mime-support, libzbar0, poppler-utils, postgresql, postgresql-contrib, unpaper, ghostscript, icc-profiles-free, qpdf, liblept5, libxml2, pngquant, zlib1g, tesseract-ocr, libatlas-base-dev, libxslt1-dev, redis-server"

    [resources.database]
    type = "postgresql"
