packaging_format = 2

id = "paperless-ngx"
name = "Paperless-ngx"
description.en = "Scan, index and archive all your physical documents"
description.fr = "Scannez, triez et archivez tous vos documents papiers"

version = "2.14.6~ynh1"

maintainers = ["Tagada"]

[upstream]
license = "GPL-3.0-or-later"
website = "https://paperless-ngx.com"
demo = "https://demo.paperless-ngx.com/"
admindoc = "https://paperless-ngx.readthedocs.io/en/latest/index.html"
userdoc = "https://paperless-ngx.readthedocs.io/en/latest/usage_overview.html"
code = "https://github.com/paperless-ngx/paperless-ngx"

[integration]
yunohost = ">= 12.0.0"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "350M"
ram.runtime = "350M"

[install]
    [install.domain]
    type = "domain"

    [install.admin]
    type = "user"

    [install.admin_pw]
    ask.en = "Please chose a password for admin user."
    type = "password"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

    [install.init_api_permission]
    ask.en = "Paperless-ngx API access list"
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/paperless-ngx/paperless-ngx/releases/download/v2.14.6/paperless-ngx-v2.14.6.tar.xz"
        sha256 = "22a0f0acd86ac25324faa4e9713d9e9d32e1f0f2002cc1dbdc7f2315282671b0"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = "paperless-ngx-.*.tar.xz"

        [resources.sources.gs]
        url = "https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs10040/ghostpdl-10.04.0.tar.xz"
        sha256 = "0603f5629bc6f567b454911d104cd96702489c9e70e577787843f480b23d4a77"

        autoupdate.upstream = "https://github.com/ArtifexSoftware/ghostpdl-downloads"
        autoupdate.strategy = "latest_github_release"
        autoupdate.version_regex = "^gs(9|1[0-9])([0-9]{2})([0-9])$"
        autoupdate.asset = "ghostpdl-.*.tar.xz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["consume", "data", "media", "imagemagick"]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    api.url = "/api/"
    api.show_tile = false
    api.auth_header = false

    share.url = "/share/"
    share.show_tile = false
    share.auth_header = false
    share.protected = true
    share.allowed = "visitors"

    [resources.ports]
    main.default = 8095

    [resources.apt]
    packages = "python3, python3-pip, python3-dev, python3-venv, default-libmysqlclient-dev, fonts-liberation, imagemagick, gnupg, libpq-dev, libmagic-dev, mime-support, libzbar0, poppler-utils, postgresql, postgresql-contrib, unpaper, ghostscript, icc-profiles-free, qpdf, liblept5, libxml2, pngquant, zlib1g, tesseract-ocr, libatlas-base-dev, libxslt1-dev, redis-server, pkg-config"

    [resources.database]
    type = "postgresql"
